# -*- mode: ruby -*-
# vi: set ft=ruby :

# Default configuration for deploying a vm running on Ubuntu 16.04
# Installs and configures golang

Vagrant.configure("2") do |config|

  config.vm.define "gosandbox" do |node|
    node.vm.box =  "ubuntu/xenial64"

    # Disable default synced folder in vagrantup
    node.vm.synced_folder ".", "/vagrant", disabled: true
    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end

    node.vm.network "private_network", ip: "192.168.50.101"

    node.vm.provision :shell, path: "bootstrap.sh"
  end

end
